In [1]:
import pandas as pd

pd.__version__

'3.0.6'

In [3]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:

# 查看数据集的行数和列数
df.shape

(10000, 11)

In [5]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [ ]:
# 查看不同燃料类型的数量
df["fuel_type"].nunique()
#nunique() 的意思是 Number of Unique Values，即不同值的数量。

3

In [ ]:
# 查看不同的燃料类型
df["fuel_type"].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [8]:
#检查每一列的缺失值数量
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [17]:
#筛选亚洲汽车
asia_car=df[df["origin"] == "Asia"]

In [18]:
asia_car["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [19]:
# 计算原始 horsepower 中位数
median_before = df["horsepower"].median()
print(median_before)
#Pandas 的 median() 默认会跳过 NaN 缺失值。

254.0

In [20]:
# 找到 horsepower 的众数
mode_value = df["horsepower"].mode()[0]
print(mode_value)

252.0

In [21]:
# 用众数填补 horsepower 的缺失值
df["horsepower"] = df["horsepower"].fillna(mode_value)

In [22]:
# 计算填补后的中位数
median_after = df["horsepower"].median()
print("Before:", median_before)
print("After:", median_after)

Before: 254.0
After: 252.0

In [ ]:
# Select two columns
selected = asia_car[["vehicle_weight", "model_year"]]
#因为你要同时选择多个列名,所以会有两层中括号

In [24]:
#选择前7行，并创建一个7*2的矩阵
selected = selected.head(7)
selected

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [25]:
X = selected.to_numpy()
print(X)
print(X.shape)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
(7, 2)

In [ ]:

# Matrix multiplication
XTX = X.T @ X
#其中@为矩阵乘法
print(XTX)
print(XTX.shape)
#因为X.T为2*7,(2*7)*(7*2)最后会生成2*2的矩阵

[[131950500  60750580]
 [ 60750580  28041424]]
(2, 2)

In [ ]:
# Inverse matrix
import numpy as np
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)
#np.linalg 是 NumPy 的线性代数模块。
#inv() 表示 inverse，即求逆矩阵。

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [29]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [32]:
# Calculate linear regression weights
w = XTX_inv @ X.T @ y
print(w)
print(w.sum())

[0.13644777 0.2327492 ]
0.36919696904925203